#!/usr/bin/env python3
import base64
import os
import sys

def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    candidates = [
        os.path.join(root_dir, "Assembly-CSharp-patch.bytes"),
        os.path.join(root_dir, "AppNew", "ThreeOneOSFive", "Assembly-CSharp-patch.bytes"),
        os.path.join(root_dir, "project-freefire_c#", "dist", "Assembly-CSharp-patch.bytes")
    ]
    
    patch_path = None
    for c in candidates:
        if os.path.isfile(c):
            patch_path = c
            break
            
    if not patch_path:
        print("Error: Assembly-CSharp-patch.bytes not found in candidate paths!", file=sys.stderr)
        sys.exit(1)
        
    print(f"Reading patch binary from: {patch_path}")
    raw_data = bytearray(open(patch_path, "rb").read())
    
    # 16-byte XOR key for anti-static analysis
    xor_key = [
        0x5A, 0xC3, 0x1F, 0x88, 0x4D, 0xE2, 0x91, 0x37,
        0xFA, 0x6E, 0xB0, 0x24, 0x75, 0x18, 0x9D, 0xCE
    ]
    
    obfuscated = bytearray(len(raw_data))
    for i in range(len(raw_data)):
        obfuscated[i] = raw_data[i] ^ xor_key[i % len(xor_key)]
        
    b64_payload = base64.b64encode(obfuscated).decode("ascii")
    
    # Format swift string literal as an array of chunks (4000 chars each)
    # using array literal + joined() instead of chained '+' operators
    # Chained '+' operators cause Swift compiler type checker stack overflow / timeout (>7 minutes or SIGSEGV)
    chunk_size = 4000
    chunks = [b64_payload[i:i+chunk_size] for i in range(0, len(b64_payload), chunk_size)]
    formatted_chunks = ",\n".join([f'        "{chunk}"' for chunk in chunks])
    
    key_hex = ", ".join([f"0x{b:02X}" for b in xor_key])
    
    swift_content = f"""// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by tools/embed_patch.py
// Encrypts and embeds Assembly-CSharp-patch.bytes into compiled Mach-O binary.
// No raw .bytes or .json files are present in the IPA package.

import Foundation

enum EmbeddedPatchData {{
    private static let xorKey: [UInt8] = [{key_hex}]

    private static let obfuscatedChunks: [String] = [
{formatted_chunks}
    ]

    private static let obfuscatedPayload: String = obfuscatedChunks.joined()

    /// Decrypts and returns the embedded Assembly-CSharp-patch.bytes directly in memory
    static func loadPatchBytes() -> Data? {{
        guard let raw = Data(base64Encoded: obfuscatedPayload) else {{ return nil }}
        var bytes = [UInt8](raw)
        let kCount = xorKey.count
        for i in 0..<bytes.count {{
            bytes[i] ^= xorKey[i % kCount]
        }}
        return Data(bytes)
    }}

    /// Generates localConfig.json in memory (no file in IPA)
    static func loadLocalConfigBytes() -> Data {{
        let jsonStr = "{{\\"testCodePatch\\":true,\\"resetGuest\\":true}}"
        return jsonStr.data(using: .utf8) ?? Data()
    }}
}}
"""
    
    out_dir = os.path.join(root_dir, "AppNew", "ThreeOneOSFive", "helpers")
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, "EmbeddedPatchData.swift")
    
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(swift_content)
        
    print(f"Successfully generated: {out_file} ({len(raw_data)} bytes embedded)")

if __name__ == "__main__":
    main()
